openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: A User Management API with MySQL and Sequelize

servers:
  - url: http://localhost:8080/api

paths:
  /login:
    post:
      summary: User login
      description: Authenticate a user and return a JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userId:
                    type: integer
                  email:
                    type: string
                    format: email
                  jwtToken:
                    type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: The user was successfully created
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/User'

    get:
      summary: Returns the list of all users
      security:
        - BearerAuth: []
      responses:
        '200':
          description: The list of users
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'


  /users/{userId}:
    get:
      summary: Get a user by id
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: The user id
      responses:
        '200':
          description: The user description by id
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: The user was not found

    put:
      summary: Update a user
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: The user id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: The user was updated
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: The user was not found

    delete:
      summary: Soft Delete a user
      description: Marks the user as deleted in DB. Data can be retrived later.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: The user id
      responses:
        '200':
          description: The user was soft deleted
        '404':
          description: The user was not found

  /users/{userId}/force:
    delete:
      summary: Hard/Force Delete a user
      description: Permanently removes a user from the system. This action cannot be undone.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: The user id
      responses:
        '200':
          description: The user was hard/force deleted from DB
        '404':
          description: The user was not found
        '403':
          description: Forbidden - User does not have permission to force delete
        '500':
          description: Internal server error


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        userId:
          type: integer
          description: The auto-generated id of the user
        firstName:
          type: string
          description: The user's first name
        lastName:
          type: string
          description: The user's last name
        email:
          type: string
          description: The user's email
        phoneNumber:
          type: string
          description: The user's phone number

    CreateUserRequest:
      type: object
      required:
        - firstName
        - email
        - password
      properties:
        firstName:
          type: string
          description: The user's first name
        lastName:
          type: string
          description: The user's last name
        email:
          type: string
          description: The user's email
        phoneNumber:
          type: string
          description: The user's phone number
        password:
          type: string
          description: The user's password

    UpdateUserRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        password:
          type: string
          format: password

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - email
        - password

    LoginResponse:
      type: object
      properties:
        message:
          type: string
        userId:
          type: integer
        email:
          type: string
          format: email
        token:
          type: string
